config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#show'

  get 'table-of-contents', to: redirect('courses')

  resources :tracks, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :courses, only: [:index, :new, :create] do
    put :update_multiple, on: :collection
  end
  resources :courses, only: [:edit, :update], path: '/'
  resources :courses, only: [:show], path: '/' do
    resources :sections, only: [:index, :new, :create, :edit]
    resources :sections, only: [:show, :update, :destroy], path: '/' do
      resources :lessons, only: [:index]
      resources :lessons, only: [:show], path: '/'
    end
  end

  resources :github_callbacks, only: [:create]
end

app/models/track.rb
class Track < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => [:slugged, :finders]

  default_scope -> { order :number }

  before_validation :set_number, on: :create
  validates :name, :presence => true, :uniqueness => true
  validates :number, :presence => true

  has_and_belongs_to_many :courses

private

  def set_number
    self.number = Track.all.last.try(:number).to_i + 1
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  authorize_resource

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
    authorize! :read, @track
    if @track.courses.count == 1
      redirect_to course_path(@track.courses.first)
    else
      render :show
    end
  end
end

app/views/tracks/index.html.erb
<% provide :title, 'Tracks' %>
<h1><%= yield :title %></h1>


<ul class="courses-list list-unstyled">
  <% @tracks.accessible_by(current_ability).each do |track| %>
    <li>
      <% if track.public? %>
        <%= link_to track.name, track_path(track) %>
      <% else %>
        <%= link_to track.name, track_path(track), class: 'lesson text-muted' %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if can? :manage, :all %>
  <hr>
  <h5><%= link_to '[view all courses]', courses_path, class: 'text-muted' %></h5>
<% end %>

app/views/tracks/show.html.erb
<% provide :title, @track.name %>
<% provide :track, @track.name %>

<ul class="breadcrumb">
  <li class="active"><%= @track.name %></li>
</ul>

<ul class="courses-list list-unstyled">
  <% @track.courses.accessible_by(current_ability).reorder(:level).each do |course| %>
    <li>
      <% if course.public? %>
        <%= link_to course.name, course_path(course) %>
      <% else %>
        <%= link_to course.name, course_path(course), class: 'lesson text-muted' %>
      <% end %>
    </li>
  <% end %>
</ul>