config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#show'

  get 'table-of-contents', to: redirect('courses')

  resources :tracks, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :courses, only: [:index, :new, :create] do
    put :update_multiple, on: :collection
  end
  resources :courses, only: [:edit, :update], path: '/'
  resources :courses, only: [:show], path: '/' do
    resources :sections, only: [:index, :new, :create, :edit]
    resources :sections, only: [:show, :update, :destroy], path: '/' do
      resources :lessons, only: [:index]
      resources :lessons, only: [:show], path: '/'
    end
  end

  resources :github_callbacks, only: [:create]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  authorize_resource

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, notice: 'Course saved.'
    else
      render 'new'
    end
  end

  def show
    begin
      @course = Course.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'Page not found'
      redirect_back(fallback_location: tracks_path) and return
    end
    authorize! :read, @course
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if params[:deleted]
      @course.restore
      redirect_to course_path(@course), notice: "Course restored."
    elsif params[:commit] == 'Save Order'
      update_section_order
      redirect_to course_path(@course), notice: "Order updated."
    else
      if @course.update(course_params)
        redirect_to course_path(@course), notice: "Course updated."
      else
        render 'edit'
      end
    end
  end

  def update_multiple
    Course.update(params[:course_attributes].keys, params[:course_attributes].values)
    redirect_to courses_path, notice: "Order Updated"
  end

private

  def course_params
    params.require(:course).permit(:name, :public, course_attributes: [:number],
                                    sections_attributes: [:name, :number, :course_id, :public],
                                    lessons_attributes: [:name, :content, :section_id, :public, :deleted_at, :video_id])
  end

  def update_section_order
    sections_params = params[:course][:sections_attributes]
    @course.sections.update(sections_params.keys, sections_params.values)
  end
end

app/views/courses/_form.html.erb
<%= render 'layouts/errors', object: @course %>
<%= form_for @course do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="checkbox">
      <%= f.label :public, class: "checkbox" do %>
        <%= f.check_box :public %>
        Public
      <% end %>
    </div>
  </div>
  <%= f.submit :class => 'btn btn-info' %>
<% end %>

app/views/courses/_update_order_form.html.erb
<%= form_for @course, method: :put do |f| %>
	<div id="course_<%= @course.id %>">
		<% if can? :update, Course %>
			<div class="btn-group">
				<%= link_to "Edit", edit_course_path(@course), id: "edit_course_#{@course.id}", class: 'btn btn-info' %>
				<% if can? :create, Section %>
					<%= link_to "New Section", new_course_section_path(@course), class: "btn btn-warning" %>
				<% end %>
				<%= f.submit 'Save Order', class: 'btn btn-danger', id: 'save_order' %>
			</div>
			<%= f.hidden_field :number, class: :course %>
			<ul class='sortable list-unstyled'>
				<%= render @course.sections, f: f %>
			</ul>
		<% else %>
			<ul class="sections-list list-unstyled"><%= render @course.sections.accessible_by(current_ability) %></ul>
		<% end %>
	</div>
<% end %>

app/views/courses/edit.html.erb
<% provide :title, "Edit #{@course.name}" %>

<h1><%= yield :title %></h1>

<div class="row">
	<div class="col-xs-6">
		<%= render 'form' %>
	</div>
</div>

app/views/courses/index.html.erb
<% provide :title, 'Courses' %>
<h1><%= yield :title %></h1>

<%= form_tag update_multiple_courses_path, method: :put do %>
  <% if can? :manage, :all %>
    <div class="btn-group">
      <%= link_to 'New Course', new_course_path, class: 'btn btn-info' %>
      <%= submit_tag "Save Order", id: "save_order", class: "btn btn-danger" %>
    </div>
  <% end %>


  <ul class="courses-list list-unstyled
    <% if can? :manage, Course %>
      sortable
    <% end %>
  ">
    <% @courses.accessible_by(current_ability).each do |course| %>
      <li>
        <% if course.public? %>
          <%= link_to course.name, course_path(course) %>
        <% else %>
          <%= link_to course.name, course_path(course), class: 'lesson text-muted' %>
        <% end %>
        <%= fields_for 'course_attributes[]', course do |course_form| %>
          <%= course_form.hidden_field :number, class: :course_number %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/courses/new.html.erb
<% provide :title, "New Course" %>

<h1><%= yield :title %></h1>

<div class="row">
	<div class="col-xs-6">
		<%= render 'form' %>
	</div>
</div>

app/views/courses/show.html.erb
<% provide :title, @course.name %>
<% provide :course, @course.name %>

<ul class="breadcrumb">
  <li class="active"><%= @course.name %></li>
</ul>

<div class="row">
  <div class="col-xs-12">
    <%= render 'update_order_form' %>
  </div>
</div>