config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#show'

  get 'table-of-contents', to: redirect('courses')

  resources :tracks, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :courses, only: [:index, :new, :create] do
    put :update_multiple, on: :collection
  end
  resources :courses, only: [:edit, :update], path: '/'
  resources :courses, only: [:show], path: '/' do
    resources :sections, only: [:index, :new, :create, :edit]
    resources :sections, only: [:show, :update, :destroy], path: '/' do
      resources :lessons, only: [:index]
      resources :lessons, only: [:show], path: '/'
    end
  end

  resources :github_callbacks, only: [:create]
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => [:slugged, :finders]

  default_scope -> { order :number }

  validates :name, :presence => true, :uniqueness => true
  validates :number, :presence => true

  has_many :sections, :dependent => :destroy
  has_many :lessons, :through => :sections

  accepts_nested_attributes_for :sections
  accepts_nested_attributes_for :lessons
end

app/controllers/chapters_controller.rb
class ChaptersController < InheritedResources::Base
  load_and_authorize_resource

  def update
    if params[:commit] == 'Save order'
      update_section_and_lesson_order
      redirect_to table_of_contents_path, notice: "Order updated."
    else
      chapter = Chapter.find(params[:id])
      if chapter.update(chapter_params)
        redirect_to chapter_path(chapter), notice: "Chapter updated."
      else
        render 'edit'
      end
    end
  end

private

  def chapter_params
    params.require(:chapter).permit(:name, :number, :public,
                                    sections_attributes: [:name, :number, :chapter_id, :public],
                                    lessons_attributes: [:name, :content, :section_id, :number, :public, :deleted_at, :video_id])
  end

  def update_section_and_lesson_order
    sections = params[:chapter][:sections_attributes].map { |section| Section.find(section[1][:id]) }
    lessons = params[:chapter][:lessons_attributes].map { |lesson| Lesson.find(lesson[1][:id]) }
    lesson_sections = LessonSection.where(section_id: sections.map(&:id), lesson_id: lessons.map(&:id))
    params[:chapter][:lessons_attributes].each do |lesson|
      lesson_section = lesson_sections.find_by(lesson_id: lesson[1][:id])
      lesson_section.update(number: lesson[1][:number])
    end
  end
end

app/views/chapters/_form.html.erb
<%= render '/layouts/errors', :object => @chapter %>
<%= chapter_and_section_form(@chapter) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :number, 'Chapter number' %>
  <%= f.text_field :number %>
  <%= f.label(:public, :class => "checkbox") do %>
    <%= f.check_box :public %>
    Public
  <% end %>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/chapters/edit.html.erb
<% provide :title, "Edit #{@chapter.name}" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/chapters/index.html.erb
<% provide :title, 'Table of contents' %>

<h1><%= yield :title %></h1>

<%= render 'lessons/search' %>

<% if can? :update, Chapter %>
  <div class="chapter">
    <%= render @chapters %>
  </div>
<% else %>
  <%= render @chapters %>
<% end %>

<% if can? :create, Chapter %>
  <p><%= link_to 'New chapter', new_chapter_path, :remote => true, :class => 'btn btn-primary btn-large', :id => 'new_chapter_link' %>
<% end%>

<% if can? :create, Section %>
  <p><%= link_to 'New section', new_section_path, :remote => true, :class => 'btn btn-warning btn-large', :id => 'new_section_link' %></p>
<% end %>

<% if can? :create, Lesson %>
  <p><%= link_to 'New lesson', new_lesson_path, :class => 'btn btn-success btn-large' %></p>
<% end %>

<% if can? :update, Lesson %>
  <%= link_to 'View deleted lessons', lessons_path + '?deleted=true' %>
<% end %>

app/views/chapters/new.html.erb
<% provide :title, "New chapter" %>

<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/chapters/new.js.erb
$(".alert").remove();
$("#new_section").remove();
$("#new_section_link").show();
$("#new_chapter_link").hide().after("<%= j render('form') %>");

app/views/chapters/show.html.erb
<% provide :title, @chapter.name %>

<h1><%= yield :title %></h1>

<ul>
  <% @chapter.sections.each do |section| %>
    <h3><%= link_to section.name, section_show_path(section), class: 'header-link' %></h3>
    <ul>
      <% section.lessons.each do |lesson| %>
        <li><%= link_to lesson.name, lesson_show_path(section, lesson) %></li>
      <% end %>
    </ul>
  <% end %>
</ul>

<% if can? :update, Chapter %>
  <p><%= link_to "Edit #{@chapter.name}", edit_chapter_path(@chapter), :class => "btn btn-large" %></p>
<% end%>

<% if can? :create, Section %>
  <p><%= link_to "New section", new_section_path, :class => "btn btn-warning btn-large" %></p>
<% end %>

app/views/chapters/update_multiple.js.erb
$('#refresh').hide();
$("input#save_order").show();