config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#show'

  get 'table-of-contents', to: redirect('courses')

  resources :tracks, only: [:index, :show]
  resources :lessons, only: [:index, :show]
  resources :courses, only: [:index, :new, :create] do
    put :update_multiple, on: :collection
  end
  resources :courses, only: [:edit, :update], path: '/'
  resources :courses, only: [:show], path: '/' do
    resources :sections, only: [:index, :new, :create, :edit]
    resources :sections, only: [:show, :update, :destroy], path: '/' do
      resources :lessons, only: [:index]
      resources :lessons, only: [:show], path: '/'
    end
  end

  resources :github_callbacks, only: [:create]
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h3>Please correct these problems:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title><%= yield :title %></title>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">

  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <% if cookies[:theme] == 'darkmode' %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/a11y-dark.min.css">
  <% else %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/a11y-light.min.css">
  <% end %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
  <script>hljs.highlightAll();</script>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= favicon_link_tag 'favicon.png' %>
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application" %>

</head>
<body class=<%= cookies[:theme] %>>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <% if notice %>
          <div class="alert alert-info"><%= notice %></div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger"><%= alert %></div>
        <% end %>

        <% if request.base_url.try('include?', 'staging') %>
          <p class='text-center text-danger' id='staging-server'><strong>STAGING SERVER &mdash; FOR TESTING ONLY</strong></p>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </div>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed btn btn-xs" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
        <ul class="nav navbar-nav">
          <%= link_to 'Tracks', tracks_path, class: 'navbar-brand' %>
          <% if @handbook %>
            <%= link_to 'Handbook', course_section_lesson_path(@handbook.section.course, @handbook.section, @handbook), class: 'navbar-brand navbar-handbook-link' %>
          <% end %>
          <li><%= yield :forward_back %></li>
        </ul>
      </div>
      <div id='navbar' class="collapse navbar-collapse">

        <ul class="nav navbar-nav pull-right">
          <li id="navbar-search">
          <%= form_tag '/lessons', method: 'get', class: 'navbar-form navbar-left' do %>
            <div class="input-group">
              <%= text_field_tag :search, nil, placeholder: 'Search lessons', class: 'form-control' %>
              <div class="input-group-btn">
                <%= button_tag 'Search', class: 'btn btn-info', id: 'lesson-search', 'aria-label': 'search' do %>
                  <span class="glyphicon glyphicon-search"></span>
                <% end %>
              </div>
            </div>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <footer class="footer">
    <div class="container">
      <p><span id='change-theme'><%= cookies[:theme] ? 'disable dark mode' : 'enable dark mode' %></span></p>
      <p>
        <% if cookies[:theme] == 'darkmode' %>
          <a href="http://www.epicodus.com" target=_blank><%= image_tag("epicodus-darkmode.png", id: "epicodus-logo", title: "Learn to program at Epicodus", alt: "Learn to program at Epicodus")%></a><br>
        <% else %>
          <a href="http://www.epicodus.com" target=_blank><%= image_tag("epicodus-logo.png", id: "epicodus-logo", title: "Learn to program at Epicodus", alt: "Learn to program at Epicodus")%></a><br>
        <% end %>
        &#169; <%= Time.zone.now.year %> <%= link_to 'Epicodus', 'http://www.epicodus.com/' %>, Inc.
      </p>
    </div>
  </footer>

  <% if Rails.env != 'test' %>
    <script>
      window.onUsersnapCXLoad = function(api) {
        api.init({
          custom: {
            course: window.location.pathname.split('/')[1]
          }
        })
        api.on('open', function(event) {
          event.api.setValue('labels', [window.location.pathname.split('/')[1]])
        })
      }
      var script = document.createElement('script');
      script.defer = 1;
      script.src = 'https://widget.usersnap.com/global/load/bfabd51e-64e5-4f0f-99d0-e88a059f7611?onload=onUsersnapCXLoad';
      document.getElementsByTagName('head')[0].appendChild(script);
    </script>
  <% end %>
</body>
</html>